pr: none
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - day7/apps/dotnetcore/Scm.Resources/*
      - day7/apps/infrastructure/templates/scm-resources-api-dotnetcore.json
      - day7/apps/pipelines/cd-scm-resources.yaml

variables:
  configuration: release
  azureSubscription: AzureDeveloperCollege
  containerRegistry: ADC-ContainerRegistry

stages:
  - stage: Build
    displayName: Build

    jobs:
      - template: jobs/build-scm-resources-api.yaml
        parameters:
          configuration: $(configuration)
          artifactDropName: drop
          buildNumber: $(Build.BuildNumber)
          containerRegistryServiceConnection: $(containerRegistry)

  - stage: Development
    displayName: Development
    dependsOn: Build

    jobs:
      - template: jobs/deploy-scm-resources-api.yaml
        parameters:
          name: Deploy Scm Resources Api
          variablesFile: ../variables/cd-scm-resources-dev.yaml
          aadVariableGroupName: Day7-AAD-Dev
          environmentName: ADC-DAY7-SCM-DEV
          azureSubscription: $(azureSubscription)
          artifactDropName: drop

  - stage: Test
    displayName: Test
    dependsOn: Development
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

    jobs:
      - template: jobs/deploy-scm-resources-api.yaml
        parameters:
          name: Deploy Scm Resources Api
          variablesFile: ../variables/cd-scm-resources-test.yaml
          aadVariableGroupName: Day7-AAD-Test
          environmentName: ADC-DAY7-SCM-TEST
          azureSubscription: $(azureSubscription)
          artifactDropName: drop
