parameters:
  configuration: release
  buildNumber: ''
  artifactDropName: drop
  containerRegistryServiceConnection: ''

jobs:
  - job: Build
    displayName: Build Scm Api
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: ../../dotnetcore/build/scm-api.yaml
        parameters:
          buildConfiguration: ${{ parameters.configuration }}
          buildNumber: ${{ parameters.buildNumber }}
          publishDockerImage: true
          containerRegistryServiceConnection: ${{ parameters.containerRegistryServiceConnection }}
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(Build.ArtifactStagingDirectory)
          artifactName: ${{ parameters.artifactDropName }}
