parameters:
  name: ""
  environmentName: ""
  azureSubscription: ""
  keyVaultVariableGroupName: ""
  containerRegistry: ""
  clusterNamespace: ""
  buildNumber: ""

jobs:
  - deployment: Deploy
    displayName: ${{ parameters.name }}
    variables:
      - group: ${{ parameters.keyVaultVariableGroupName }}
    pool:
      vmImage: ${{ variables.vmImage }}
    environment: ${{ parameters.environmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadPipelineArtifact@1
              inputs:
                artifactName: "manifests"
                downloadPath: "$(System.ArtifactsDirectory)/manifests"
            - task: DownloadPipelineArtifact@1
              inputs:
                artifactName: "secrets"
                downloadPath: "$(System.ArtifactsDirectory)/secrets"
            - task: replacetokens@3
              inputs:
                targetFiles: "$(System.ArtifactsDirectory)/secrets/secrets.yml"
                encoding: "auto"
                writeBOM: true
                actionOnMissing: "warn"
                keepToken: false
                tokenPrefix: "#{"
                tokenSuffix: "}#"
            - task: KubernetesManifest@0
              displayName: Create imagePullSecret
              inputs:
                action: createSecret
                secretName: regcred
                namespace: ${{ parameters.clusterNamespace }}
                dockerRegistryEndpoint: ${{ parameters.containerRegistry }}
            - task: KubernetesManifest@0
              displayName: Deploy secrets to Kubernetes cluster
              inputs:
                action: deploy
                namespace: ${{ parameters.clusterNamespace }}
                manifests: |
                  $(System.ArtifactsDirectory)/secrets/secrets.yml
            - task: KubernetesManifest@0
              displayName: Deploy to Kubernetes cluster
              inputs:
                action: deploy
                namespace: ${{ parameters.clusterNamespace }}
                manifests: |
                  $(System.ArtifactsDirectory)/manifests/scm-deploy.yml
                  $(System.ArtifactsDirectory)/manifests/scm-ingress.yml
                  $(System.ArtifactsDirectory)/manifests/scm-svc.yml
                imagePullSecrets: |
                  regcred
                containers: |
                  azuredevcollege.azurecr.io/adcday7/scmapi:${{ parameters.buildNumber }}
