parameters:
  name: ""
  environmentName: ""
  artifactDropName: terraformplan
  environmentServiceNameAzureRM: ""

jobs:
  - deployment: Deploy
    displayName: ${{ parameters.name }}
    pool:
      vmImage: ubuntu-latest
    environment: ${{ parameters.environmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: TerraformTaskV1@0
              inputs:
                provider: 'azurerm'
                command: 'apply'
                commandOptions: './${{ parameters.artifactDropName }}/tfplan -auto-approve'
                environmentServiceNameAzureRM: ${{ parameters.environmentServiceNameAzureRM }}