apiVersion: v1
kind: Secret
metadata:
  name: uisettings
type: Opaque
stringData:
  settings.js: |-
    var uisettings = {
      "endpoint": "https://#{adcday7HOSTNAME}#/api/contacts/",
      "resourcesEndpoint": "https://#{adcday7HOSTNAME}#/api/resources/",
      "searchEndpoint": "https://#{adcday7HOSTNAME}#/api/search/",
      "reportsEndpoint": "https://#{adcday7HOSTNAME}#/api/visitreports/",
      "enableStats": true,
      "aiKey": "#{adcday7APPINSIGHTSKEYDEC}#",
      "clientId": "#{adcday7AADFECLIENTID}#",
      "tenantId": "#{adcday7AADTENANTIDDEC}#",
      "audience": "#{adcday7AADCLIENTIDURIDEC}#"
    }