apiVersion: v1
kind: Secret
metadata:
  name: scmsecrets
type: Opaque
data:
  "AADCLIENTID": "#{adcday7AADCLIENTID}#"
  "AADCLIENTIDURI": "#{adcday7AADCLIENTIDURI}#"
  "AADDOMAIN": "#{adcday7AADDOMAIN}#"
  "AADTENANTID": "#{adcday7AADTENANTID}#"
  "APPINSIGHTSKEY": "#{adcday7APPINSIGHTSKEY}#"
  "CONTACTSLISTENCONNSTR": "#{adcday7CONTACTSLISTENCONNSTR}#"
  "CONTACTSLISTENENTITYCONNSTR": "#{adcday7CONTACTSLISTENENTITYCONNSTR}#"
  "CONTACTSSENDCONNSTR": "#{adcday7CONTACTSSENDCONNSTR}#"
  "COSMOSENDPOINT": "#{adcday7COSMOSENDPOINT}#"
  "COSMOSPRIMARYKEY": "#{adcday7COSMOSPRIMARYKEY}#"
  "COSMOSSECONDARYKEY": "#{adcday7COSMOSSECONDARYKEY}#"
  "RESOURCESCONNECTIONSTRING": "#{adcday7RESOURCESCONNECTIONSTRING}#"
  "FUNCTIONSCONNECTIONSTRING": "#{adcday7FUNCTIONSCONNECTIONSTRING}#"
  "SEARCHNAME": "#{adcday7SEARCHNAME}#"
  "SEARCHPRIMARYKEY": "#{adcday7SEARCHPRIMARYKEY}#"
  "SQLDBCONNECTIONSTRING": "#{adcday7SQLDBCONNECTIONSTRING}#"
  "TAENDPOINT": "#{adcday7TAENDPOINT}#"
  "TAKEY": "#{adcday7TAKEY}#"
  "THUMBNAILLISTENCONNSTR": "#{adcday7THUMBNAILLISTENCONNSTR}#"
  "THUMBNAILSENDCONNSTR": "#{adcday7THUMBNAILSENDCONNSTR}#"
  "VRLISTENCONNSTR": "#{adcday7VRLISTENCONNSTR}#"
  "VRSENDCONNSTR": "#{adcday7VRSENDCONNSTR}#"
