apiVersion: apps/v1 
kind: Deployment
metadata:
  name: scm-deploy 
  labels:
    application: scmcontacts
    service: scmapi
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      application: scmcontacts
      service: scmapi
  template:
    metadata:
      labels:
        application: scmcontacts
        service: scmapi
    spec:
      automountServiceAccountToken: false
      containers:
        - name: application
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          image: azuredevcollege.azurecr.io/adcday7/scmapi
          env:
            - name: ConnectionStrings__DefaultConnectionString
              valueFrom:
                secretKeyRef:
                  name: scmsecrets
                  key: SQLDBCONNECTIONSTRING
            - name: AzureAdOptions__Domain
              valueFrom:
                secretKeyRef:
                  name: scmsecrets
                  key: AADDOMAIN            
            - name: AzureAdOptions__TenantId
              valueFrom:
                secretKeyRef:
                  name: scmsecrets
                  key: AADTENANTID
            - name: AzureAdOptions__ClientId
              valueFrom:
                secretKeyRef:
                  name: scmsecrets
                  key: AADCLIENTID
            - name: AzureAdOptions__ClientIdUri
              valueFrom:
                secretKeyRef:
                  name: scmsecrets
                  key: AADCLIENTIDURI
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: scmsecrets
                  key: APPINSIGHTSKEY
            - name: EventServiceOptions__ServiceBusConnectionString
              valueFrom:
                secretKeyRef:
                  name: scmsecrets
                  key: CONTACTSSENDCONNSTR
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5000