name: day2-scm-resourcesapi

on:
  push:
    branches:
      - master
    paths:
      - 'day2/apps/infrastructure/bicep/scm-resourcesapi.bicep'
      - 'day2/apps/dotnetcore/Scm.Resources/**'

  pull_request:
    branches:
      - master
    paths:
      - 'day2/apps/infrastructure/bicep/scm-resourcesapi.bicep'
      - 'day2/apps/dotnetcore/Scm.Resources/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_PACKAGE_PATH: 'publish/scmresourcesapi'
      RESIZER_PACKAGE_PATH: 'publish/resizer'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Transpile bicep files
        run: az bicep build -f ./day2/apps/infrastructure/bicep/scm-resourcesapi.bicep

      - name: Archive ARM Templates artifacts
        uses: actions/upload-artifact@v2
        #if: github.event_name == 'push'
        with:
          name: bicep
          path: ./day2/apps/infrastructure/bicep/scm-resourcesapi.json
          retention-days: 30
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      
      - name: Build and publish SCM Resources API
        working-directory: ./day2/apps/dotnetcore/Scm.Resources/Adc.Scm.Resources.Api
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o './${{ env.API_PACKAGE_PATH }}'

      - name: Archive api dotnetcore package artifacts
        uses: actions/upload-artifact@v2
        #if: github.event_name == 'push'
        with:
          name: scmresourcesapi
          path: './day2/apps/dotnetcore/Scm.Resources/Adc.Scm.Resources.Api/${{ env.API_PACKAGE_PATH }}/'
          retention-days: 30

      - name: Build and publish SCM ImageResizer
        working-directory: ./day2/apps/dotnetcore/Scm.Resources/Adc.Scm.Resources.ImageResizer
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o './${{ env.RESIZER_PACKAGE_PATH }}'

      - name: Archive ImageResizer dotnetcore package artifacts
        uses: actions/upload-artifact@v2
        #if: github.event_name == 'push'
        with:
          name: scmresourcesapi
          path: './day2/apps/dotnetcore/Scm.Resources/Adc.Scm.Resources.ImageResizer/${{ env.RESIZER_PACKAGE_PATH }}/'
          retention-days: 30