name: Day4 - Visitreports API
on:
  push:
    branches: [ master ]
    paths:
      - .github/workflows/day4-scm-visitreports.yaml
      - day4/apps/nodejs/visitreport/**
      - day4/apps/infrastructure/bicep/**
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/day4-scm-visitreports.yaml
      - day4/apps/nodejs/visitreport/**
      - day4/apps/infrastructure/bicep/**

env:
  RESOURCE_GROUP_NAME_PREFIX: SCM-DEVD4
  TEMPLATE_NAME: visitreportsmain
  ENVIRONMENT_NAME: dev

jobs:
  extract-arm-template:
    if: ${{ github.repository == 'azuredevcollege/trainingdays' }}
    env:
      TEMPLATE_PATH: day4/apps/infrastructure/bicep/visitreports
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Transpile bicep files
        run: az bicep build -f ${{env.TEMPLATE_NAME }}.bicep
        working-directory: ${{ env.TEMPLATE_PATH }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: template
          path: ${{ env.TEMPLATE_PATH }}/${{env.TEMPLATE_NAME }}.json
          if-no-files-found: error
          retention-days: 90

  deploy-arm-template:
    if: ${{ github.ref == 'refs/heads/master' && github.repository == 'azuredevcollege/trainingdays' }}
    runs-on: ubuntu-latest
    needs: extract-arm-template
    environment: day4-scm-dev
    outputs:
      visitreportsWebAppName: ${{ steps.arm.outputs.visitreportsWebAppName }}
      textanalyticsFunctionName: ${{ steps.arm.outputs.textanalyticsFunctionName }}
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Download the arm template
        uses: actions/download-artifact@v2
        with:
          name: template
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Azure Resource Manager (ARM) Template
        id: arm
        uses: Azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME_PREFIX }}-${{ env.GITHUB_REPOSITORY_OWNER_PART }}
          template: ${{env.TEMPLATE_NAME }}.json
          deploymentMode: Incremental
          parameters: > # Lines are joined with spaces
            env=${{ env.ENVIRONMENT_NAME }}

  build-and-deploy-api:
    if: ${{ github.ref == 'refs/heads/master' && github.repository == 'azuredevcollege/trainingdays' }}
    runs-on: ubuntu-latest
    environment: day4-scm-dev
    needs:
      - deploy-arm-template
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Cache npm dependencies to speed up deployment
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('day4/apps/nodejs/visitreport/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: npm install, build, and test
        working-directory: day4/apps/nodejs/visitreport
        run: | # The following lines are joined by a newline (\n) character
          npm install
          npm run build --if-present
          npm run test --if-present
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure WebApp
        uses: azure/webapps-deploy@v2.1.6
        with:
          package: day4/apps/nodejs/visitreport
          app-name: ${{ needs.deploy-arm-template.outputs.visitreportsWebAppName }}

  build-and-deploy-textanalytics:
    if: ${{ github.ref == 'refs/heads/master' && github.repository == 'azuredevcollege/trainingdays' }}
    runs-on: ubuntu-latest
    environment: day4-scm-dev
    needs:
      - deploy-arm-template
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Cache npm dependencies to speed up deployment
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('day4/apps/nodejs/textanalytics/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: npm install, build, and test
        working-directory: day4/apps/nodejs/textanalytics
        run: | # The following lines are joined by a newline (\n) character
          npm install
          npm run build --if-present
          npm run test --if-present
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure WebApp
        uses: azure/functions-action@v1
        with:
          app-name: ${{ needs.deploy-arm-template.outputs.textanalyticsFunctionName }}
          package: day4/apps/nodejs/textanalytics
